django_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path, re_path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # /music/<album_id>
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),
    re_path(r'album/(?P<pk>[0-9]+)/update/', views.AlbumUpdate.as_view(), name='album-update'),
    re_path(r'album/(?P<pk>[0-9]+)/delete/', views.AlbumDelete.as_view(), name='album-delete'),

    path('register/', views.UserFormView.as_view(), name='register')
    
]

music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(max_length=500)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    # information about your class
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Album
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User object if cerdentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form action="" method="POST" enctype="multipart/form-data" class="form-horizontal">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Viberr{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
        <link href="https://fonts.googleapis.com/css?family=Merienda" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
            <div class="container-fluid">
        
                <div class="navbar-header">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavBar">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                    <a href="{% url 'music:index' %}" class="navbar-brand">Viberr</a>
                </div>
        
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
        
                        <li class="">
                            <a href="{% url 'music:index' %}" class="nav-link"><i class="fas fa-compact-disc"></i>&nbsp;Albums</a>
                        </li>
        
                        <li class="">
                            <a href="#" class="nav-link"><i class="fas fa-music"></i>&nbsp;Music</a>
                        </li>
        
                    </ul>
        
                    <form action="#" method="get" role="search" class="form-inline my-2 my-lg-0">
                        <div class="form-group">
                            <input type="text" class="form-control mr-sm-2" name="q" value="">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
        
                    <ul class="nav navbar-nav ml-auto">
        
                        <li class="">
                            <a href="{% url 'music:album-add' %}" class="nav-link"><i class="fas fa-plus"></i>&nbsp;Add Album</a>
                        </li>
        
                        <li class="">
                            <a href="#" class="nav-link"><i class="fas fa-power-off"></i>&nbsp;Logout</a>
                        </li>
        
                    </ul>
                </div>
        
            </div>
        </nav>
        {% block body %}

        {% endblock %}
    </body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}

{% block body %}

    <img src="{{ album.album_logo.url }}" height="300" width="300">

    <h1>{{ album.album_title }}</h1>
    <h2>{{ album.artist }}</h2>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    {% for song in album.song_set.all %}
        {{ song.song_title }}
        {% if song.is_favourite %}
        &nbsp;<i class="fas fa-star"></i>
        {% endif %}
    <br>
    {% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    {% if object_list %}

        <ul>
            {% for album in object_list %}
            <li>
                <a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a>
                <form action="{% url 'music:album-update' album.id %}" method="" style="display: inline">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}">
                    <button type="submit" class="btn btn-default btn-sm">
                        <i class="fas fa-edit"></i>
                    </button>
                </form>
                <form action="{% url 'music:album-delete' album.id %}" method="POST" style="display: inline">
                    {% csrf_token %}
                    <input type="hidden" name="album_id" value="{{ album.id }}">
                    <button type="submit" class="btn btn-default btn-sm">
                        <i class="fas fa-trash"></i>
                    </button>
                </form>
            </li>
            {% endfor %}
        </ul>

    {% else %}

        <h3>There are no albums in the collection.</h3>

    {% endif %}
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a New Account</h3>
                    <form action="" method="POST" enctype="multipart/form-data" class="form-horizontal">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}